#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/Users/jhl/Projects/gwt/gwt-mac-1.5.3/gwt-user.jar:/Users/jhl/Projects/gwt/gwt-mac-1.5.3/gwt-dev-mac.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.algorithmstudy.visualizer.AlgorithmVisualizer/AlgorithmVisualizer.html;
